@startuml
  hide footbox
  title
    Sequence diagram title
    on several lines
  end title
  participant A as "nonono"
  participant B as "toto"
  A -> B: ok!
  A o-[#555]->x "xB": hello
  |||
  create actor test as "test"
  test ->]: nono!
  ||55||
  activate test #ccc
  deactivate test
  [->x "tust": ""maybe""
  tust x<-o]: okk
  note left
    This is **bold**
  end note
@enduml

@startuml
participant Alice
actor Bob

ref over Alice, Bob: init

Alice -> Bob : hello

ref over Bob , Alice
  This can be on
  several lines
end ref
@enduml

@startuml
participant Alice
participant "The **Famous** Bob" as Bob

Alice -> Bob : hello --there--
... Some ~~long delay~~ ...
Bob -> Alice : ok
note left
  This is **bold**
  This is //italics//
  This is ""monospaced""
  This is --stroked--
  This is __underlined__
  This is ~~waved~~
end note

Alice -> Bob : A //well formatted// message
note right of Alice
 This is <back:cadetblue><size:18>displayed</size></back>
 __left of__ Alice.
end note
note left of Bob
 <u:red>This</u> is <color #118888>displayed</color>
 **<color purple>left of</color> <s:red>Alice</strike> Bob**.
end note
note over Alice, Bob
 <w:#FF33FF>This is hosted</w> by <img sourceforge.jpg>
end note
@enduml
